apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-carrier-allchannel
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-carrier-allchannel
  chart:
    git: ssh://git@github.com/adityajoshi12/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: carrier-net
      network:
        version 2.2.2
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://40.80.95.60:8200
      authpath: devcarrier-net-auth
      adminsecretprefix: secretv2/data/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secretv2/data/crypto/peerOrganizations/carrier-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.supplychain-net:7050
    channeltx: |-
      CtkDChgKFggCGgYIr9iElgYiCmFsbGNoYW5uZWwSvAMKuQMKCmFsbGNoYW5uZWwSRhI0CgtBcHBs
      aWNhdGlvbhIlEg4KCmNhcnJpZXJNU1ASABITCg9tYW51ZmFjdHVyZXJNU1ASABoOCgpDb25zb3J0
      aXVtEgAa4gIStgIKC0FwcGxpY2F0aW9uEqYCCAESEwoPbWFudWZhY3R1cmVyTVNQEgASDgoKY2Fy
      cmllck1TUBIAGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiLAoLRW5kb3JzZW1lbnQSHRITCAMSDwoLRW5kb3Jz
      ZW1lbnQQAhoGQWRtaW5zIjUKFExpZmVjeWNsZUVuZG9yc2VtZW50Eh0SEwgDEg8KC0VuZG9yc2Vt
      ZW50EAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0
      ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGicKCkNvbnNvcnRpdW0SGRIXChVT
      dXBwbHlDaGFpbkNvbnNvcnRpdW0=