apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: ssh://git@github.com/adityajoshi12/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://40.80.95.60:8200
      role: vault-role
      authpath: devsupplychain-net-auth
      secretprefix: secretv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIJYAAVSF/2G9yiESldWMAUiPT3JIGMtr4IOJhx5UOPxsEqJeCp9eCpxeCngKWggBEAEaBgis
      loKWBiIKc3lzY2hhbm5lbCpAMjZkZjkxZTVlMzhmNWEyZjM2ZDcwNGRlYmEwMzUyNWJkYTlhYzg5
      YjlkNDg3NzdkYzQwYzNlNzg2ZTYyZTNlMBIaEhjcyE1nl4ZaJ/n6VfbAfyLo1t1SdR3KgcwSn10K
      nF0SmV0SlSsKB09yZGVyZXISiSsSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVUlhhV3RWMzIwdHRoNHlyeVo1bk42SEMweUE4d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpBeU1UY3lPREExV2hjTk1qVXdOREl4TVRjeU9EQTFX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJLNHhp
      ZThRdFAyblRpdVdNMUVCdFE4enVQY0xsQ3lKZ2srWmdXc3ZraVVvNEdJcmdGZGkKY0R0S1ZmSTV2
      N0JsbUpDVEQ2ZnRjb0FFUTVBTVE2UWpTK2lqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzNHWFQ0SzRMcUZPSDBwUDkva2RlODVF
      eDl3REFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQWhiSGlpYlI5OWM0eTlJeTZkQWllRHUwb1l5
      bGxDdzVDdkxqdjdEZ3YKU1BzQ0lEY3Z6dERGSmM4bEtUMCs4T3NoRkVJRkJDRHRsenlSbTN2ZFRi
      c0lPVGVYCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVRk9INXBDc0RvNE05bGIrUFpPVTlxQUZPOTBNd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpBeU1UY3pOakF3V2hjTk1q
      TXdOekF5TVRjME1UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFazRoM09UK3AzbnJUdncvajdWM3hFZU11SGRs
      eXhCOWkKZ1A4Y2FsVjZxdHAwZE0zc2lLeC9YUHAxRzV4akplWWRZekE0UEUwKy8rMFVMb2VOdTFn
      eSthT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTOTJJbTYrWFExClFESDdPZk9BaTNuSFlUL1Y2REFmQmdOVkhTTUVHREFXZ0JT
      M0dYVDRLNExxRk9IMHBQOS9rZGU4NUV4OXdEQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05UZG1aalZpTkdRNExXZDBhSHA0TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUlJQXpWVUExS2lHdHF5N3IvMDMzNGhIVXVoN2g2TmNTdDF1a1h5ejNTdWNBaUFp
      bVhyTit1c2Z2MjE4ClpmeFhMNHR2Wk1YRDlYUStsQ3ZqN05mVlQ3Z2FzZz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVJYYVd0VjMyMHR0aDR5cnlaNW5ONkhDMHlBOHdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056QXlNVGN5T0RBMVdoY05NalV3
      TkRJeE1UY3lPREExV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCSzR4aWU4UXRQMm5UaXVXTTFFQnRROHp1UGNMbEN5SmdrK1pnV3N2a2lVbzRHSXJn
      RmRpCmNEdEtWZkk1djdCbG1KQ1RENmZ0Y29BRVE1QU1RNlFqUytpalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlMzR1hUNEs0THFG
      T0gwcFA5L2tkZTg1RXg5d0RBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFoYkhpaWJSOTljNHk5
      SXk2ZEFpZUR1MG9ZeWxsQ3c1Q3ZManY3RGd2ClNQc0NJRGN2enRERkpjOGxLVDArOE9zaEZFSUZC
      Q0R0bHp5Um0zdmRUYnNJT1RlWAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0
      cmljdGlvbnMSCBoGQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMa
      ihIKDUNvbnNlbnN1c1R5cGUS+BES7REKCGV0Y2RyYWZ0EuARCskRChhvcmRlcmVyMS5zdXBwbHlj
      aGFpbi1uZXQQijca0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJ
      QkFnSVVUVG5vOWFSZVQ3RDVXdVQxdGgvMkMzTVIyTVV3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0Zw
      YmkxdVpYUXcKSGhjTk1qSXdOekF5TVRjek5qQXdXaGNOTWpNd056QXlNVGMwTVRBd1dqQnhNUXN3
      Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3
      RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFE
      RXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DQUFSeWJ5cG5idit6R0xLeE1JakVNdGNNL2NLaQpxWHNsanp2SmhMbzR3dFMw
      UEd5cE1uRUF2b1RSVys1c3phaHVDZ3o3QmlDcmhRSlJkUzd5c0p1UW52SFJvNElCCk1EQ0NBU3d3
      RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYK
      QlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTdjBnZ2k5ZzkwOXdzVVZzWmVq
      SHRCb0ZKcQp0REFmQmdOVkhTTUVHREFXZ0JTM0dYVDRLNExxRk9IMHBQOS9rZGU4NUV4OXdEQS9C
      Z05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnla
      WEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJ
      anA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2li
      M0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnla
      WElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFKOUpyVVBnbEZZQUpTR2oKVmxMSVNsWlhM
      TmVRenFGc0d1YUFFTjF4dVQwaEFpQnV6cTgrRzZqV1YxNFpvU1ZaUXdxUHB6QWNIeUV1RUU4cQpz
      SFRoYXk2eThBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi0wgtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVUVG5vOWFSZVQ3RDVXdVQxdGgvMkMzTVIy
      TVV3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dH
      UVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekF5TVRjek5qQXdX
      aGNOTWpNd056QXlNVGMwTVRBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNO
      VEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURW
      UVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJp
      MXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSeWJ5cG5idit6R0xLeE1J
      akVNdGNNL2NLaQpxWHNsanp2SmhMbzR3dFMwUEd5cE1uRUF2b1RSVys1c3phaHVDZ3o3QmlDcmhR
      SlJkUzd5c0p1UW52SFJvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpR
      UVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0Ex
      VWREZ1FXQkJTdjBnZ2k5ZzkwOXdzVVZzWmVqSHRCb0ZKcQp0REFmQmdOVkhTTUVHREFXZ0JTM0dY
      VDRLNExxRk9IMHBQOS9rZGU4NUV4OXdEQS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRY
      QndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1H
      d0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3
      aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1W
      MElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJ
      aEFKOUpyVVBnbEZZQUpTR2oKVmxMSVNsWlhMTmVRenFGc0d1YUFFTjF4dVQwaEFpQnV6cTgrRzZq
      V1YxNFpvU1ZaUXdxUHB6QWNIeUV1RUU4cQpzSFRoYXk2eThBPT0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICACBoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCA
      gIAxGICAQBoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxK9LwoLQ29uc29ydGl1bXMSrS8S4i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLILhKxFwoP
      bWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1TUBKBBi0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVU5NdllYdDdJOGd4
      RjVMck1aMk1UWG1KSndSMHdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4
      TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhR
      d0hoY05Nakl3TnpBeU1UY3pNREE1V2hjTk1qVXdOREl4TVRjek1EQTVXakJrTVFzd0NRWURWUVFH
      CkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFU
      QmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1Ix
      Y21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQklOZUVqWVAzNEJ4
      MVRHSGMzekxNbjVBSkRGN0FoMTVSR3A2Cjl6aVJ1Z3RpMU5sUG1qYTU3Zi9TQkRHNDBHcUNLWmhH
      U3JQZHFpTi81djYrbGtKL3lJU2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQ
      QVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJUM3J4NTIwRllzcGtZQQpBeEJRY0ptL2JMRHp1ekFL
      QmdncWhrak9QUVFEQWdOSUFEQkZBaUE4NndlN0NMVFlOQnU2S1M1bUtXZHdwTHA5CnJmWStQTVJM
      cTJ5cStRZDhXUUloQVBqcktOWnhDZDVsaUdmenhMYU4zbWlQT1ppTkpOS1AvVjdRK3l2TFk2a00K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJREVUQ0NBcmVnQXdJQkFnSVVWTThzMHBxK2RhREFyZUZreWVGaDlxeS9lZll3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056QXlNVGN6T0RBd1doY05N
      ak13TnpBeU1UYzBNekF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNM
      ak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6QU1C
      Z05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZRUURE
      QlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6
      ajBEQVFjRFFnQUVpUDIwRkdjMm9FTUU4ZldKK3JWMUh6ZmJpbHM3cU13cGlyZDdab1hYL3kvRmlV
      NHJqWHdxCjExbWtTd093elhZVStueitSZlR4NXVidmVXNEVXRmZVZWFPQ0FTSXdnZ0VlTUE0R0Ex
      VWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFiWSs5djhq
      RUVwVTJHTW1vNFNsb0xYZW9OVmpBZgpCZ05WSFNNRUdEQVdnQlQzcng1MjBGWXNwa1lBQXhCUWNK
      bS9iTER6dXpBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAxWWpaalltWTNaRGs1TFd4bmMz
      YzVNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpvaWRI
      SjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldGdWRX
      WmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1poClkz
      UjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdO
      SUFEQkYKQWlFQThYWDhSNGhTbDFZc2Q5Rjg2c1FreGw5NVRXeDdKV3E4QWpqVnpmZHFFR01DSUY2
      dlpPY2p2aUx6eXZ5WApNOTR4ejlURi90c2xwQ2t1Q1YrRHd1SjZRTHFHCi0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlDRERDQ0FiS2dBd0lCQWdJVU5NdllYdDdJOGd4RjVMck1aMk1UWG1KSndSMHdDZ1lJS29a
      SXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdO
      VkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpBeU1UY3pNREE1V2hj
      Tk1qVXdOREl4TVRjek1EQTVXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25W
      eWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhK
      bGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000
      OUFnRUdDQ3FHU000OUF3RUhBMElBQklOZUVqWVAzNEJ4MVRHSGMzekxNbjVBSkRGN0FoMTVSR3A2
      Cjl6aVJ1Z3RpMU5sUG1qYTU3Zi9TQkRHNDBHcUNLWmhHU3JQZHFpTi81djYrbGtKL3lJU2pRakJB
      TUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FX
      QkJUM3J4NTIwRllzcGtZQQpBeEJRY0ptL2JMRHp1ekFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUE4
      NndlN0NMVFlOQnU2S1M1bUtXZHdwTHA5CnJmWStQTVJMcTJ5cStRZDhXUUloQVBqcktOWnhDZDVs
      aUdmenhMYU4zbWlQT1ppTkpOS1AvVjdRK3l2TFk2a00KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJN
      U1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zErYWCgpjYXJyaWVyTVNQEqcWGsMUCgNNU1ASuxQS
      sBQSrRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitUQ0NB
      WjZnQXdJQkFnSVVWR3lWUm5xNjl5YWlURENJSVRLcUxWd0hjODB3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFX
      VnlMVzVsZERBZUZ3MHkKTWpBM01ESXhOek15TVRKYUZ3MHlOVEEwTWpFeE56TXlNVEphTUZveEN6
      QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJt
      UnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNp
      MXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUMkZsekZ3eFRvNWNsUWVz
      eElNenZPWnVSZjdHNldvZFQvWHdkZHBRSWFWNG9KNFZBVWU4NkFUak9tbFhRKwpQUEM5VUkxK1pj
      THpZdGpVa29sOUFBdVBvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93
      UUVBd0lCcGpBZEJnTlZIUTRFRmdRVW5vRzZDVDB4bWl5Si9SV0U5TGJQOUNSUTZ1TXdDZ1lJS29a
      SXpqMEUKQXdJRFNRQXdSZ0loQU1Ocy9IbDIyS2o3amQ4NTdXM2REQ2RsUWJVbFJTSExNbFdWRGVa
      QjJUUEdBaUVBZ0prNAo3d0g4UlQ3T0ZIN1NIUmkvNlFZRVBMM0x3cytXVjZONkJPQUhyNzQ9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUM3akNDQXBTZ0F3SUJBZ0lVR25TRnQ1S1R1dGkvR0FSUjZKQnFtQ1RmTzdnd0NnWUlLb1pJemow
      RUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1
      allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNREl4TnpRME1EQmFGdzB5TXpBM01ESXhOelE1TURC
      YU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1
      a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFV
      RUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNYR3ZBY2dmMGo4L1BaaWN4cU54emkKMStJ
      dEY4T3QvdmhWdDdCKzlNaitwbnhHRm9xanU0elpqMEhYOWFtQzdLSTBrNmlYSTJpOVlzdkhoanZT
      NUlBWQpvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3
      SFFZRFZSME9CQllFCkZQQ2ZnSVlHRW9WRm8rbFYwd0o2a3hPQ0JXWEZNQjhHQTFVZEl3UVlNQmFB
      Rko2QnVnazlNWm9zaWYwVmhQUzIKei9Ra1VPcmpNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6
      TFRVMVltSTJOR0kyTmpndE4ybzJjWE13Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2
      ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1pt
      YVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0
      YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJ
      emowRUF3SURTQUF3UlFJaEFNN2doUmdUd2hmNkV0dDh1QmI1N29LRk1leGxLaUNSSDY3Z2lHd2xL
      bnU0CkFpQW5zYkI0dWdmOWZ0WlhwODFLaXJVSEFNanNmdm50bnB1aDF0Tzl6U2NZaFE9PQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVWR3lWUm5xNjl5YWlURENJSVRLcUxWd0hj
      ODB3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dG
      UVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01ESXhOek15TVRKYUZ3MHlO
      VEEwTWpFeE56TXlNVEphTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWti
      MjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdB
      MVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkMKQUFUMkZsekZ3eFRvNWNsUWVzeElNenZPWnVSZjdHNldvZFQvWHdkZHBRSWFWNG9KNFZBVWU4
      NkFUak9tbFhRKwpQUEM5VUkxK1pjTHpZdGpVa29sOUFBdVBvMEl3UURBUEJnTlZIUk1CQWY4RUJU
      QURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVW5vRzZDVDB4bWl5Si9S
      V0U5TGJQOUNSUTZ1TXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQU1Ocy9IbDIyS2o3amQ4NTdX
      M2REQ2RsUWJVbFJTSExNbFdWRGVaQjJUUEdBaUVBZ0prNAo3d0g4UlQ3T0ZIN1NIUmkvNlFZRVBM
      M0x3cytXVjZONkJPQUhyNzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoG
      QWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5k
      b3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVh
      ZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJz
      EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hh
      bm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdv
      cml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhAS
      Bgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHlj
      aGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQS
      CgoICgRWMl8wEgAaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIi
      CgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRt
      aW5zEAIaBkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
