apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: ssh://git@github.com/adityajoshi12/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://40.80.95.60:8200
      role: vault-role
      authpath: devsupplychain-net-auth
      secretprefix: secretv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIE8KJPQgc6hAyy0k3exT9WHuxGQU4JZap4WWbqeZFUV7EppeCpdeCpReCngKWggBEAEaBgiw
      2ISWBiIKc3lzY2hhbm5lbCpAMmVmNmM3ZmQ5N2EzNGE1NTc2MGJhYWM4NjMxMTQ0NGI1NzQzNDhm
      MjkwM2M5NTMyMTA5NDIzYjViYTNlNTJmYhIaEhjmwVsvmoG73/ID9M1allyXz1Tr6RCsqfsSl10K
      lF0SkV0SjSsKB09yZGVyZXISgSsSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVSkIzSE1LMzJGU1k0b1FZL0MyRXV2d25MZXA4d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpBek1EUXlORE0zV2hjTk1qVXdOREl5TURReU5ETTNX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJQTXU5
      MTFUc2szTmZTZjBQVFR0TWFrTXpOTi83M0ZsWURYVjZ4akt0Yk0xUy85Vkx6OVkKdVZGcVR0V0dG
      YTZMbWxlVWZXU0VUZ20yMk5JZ3BKN2VJS0tqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUTdLMy94NWQvT2NrL3JjNFFadjVvRll5
      VFVoREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTdyV3JTZEdFS25mRWFkWitwbGtBWkM0MU94
      NUtiVlZHM211bDhqSXoKb1FvQ0lGNG96aklmcGp1RUl0dkxUNTF0NDVsTjJHUlpXaFdUdE1QeER2
      ZXRxV1d6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVRE95RDU5SHZEa2FOTUJHUFN4YU9rRGN1anBVd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpBek1EUXpNakF3V2hjTk1q
      TXdOekF6TURRek56QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNDJlMWFGLzhVYWxLMVVvWE5IdFdVK2lZRHJo
      d2Z4N2YKVHZ0Y1FBV0hVR2VUNzVVbkhKb1R2U094UFFvRTBFcEdZVmpSWGZxVlppc2tNdnFLTFlW
      S3A2T0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRVEFibVFBNlNWCmZTMU9qcGVTQ1BvYzlkd2s2ekFmQmdOVkhTTUVHREFXZ0JR
      N0szL3g1ZC9PY2svcmM0UVp2NW9GWXlUVWhEQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05UZG1aalZpTkdRNExXcHFiSEp3TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUwyUlJQSDNGeE1VK2hmUmFneWFVcldBTFI0MXJFYjJscVlZejFPOXRZYW9BaUI1
      VEFVRmt1dGliRXMwClk3U2JKc3IrRWRvZklvajVRZ1pEY01qZmF4cFBwdz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVUpCM0hNSzMyRlNZNG9RWS9DMkV1dnduTGVwOHdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056QXpNRFF5TkRNM1doY05NalV3
      TkRJeU1EUXlORE0zV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCUE11OTExVHNrM05mU2YwUFRUdE1ha016Tk4vNzNGbFlEWFY2eGpLdGJNMVMvOVZM
      ejlZCnVWRnFUdFdHRmE2TG1sZVVmV1NFVGdtMjJOSWdwSjdlSUtLalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlE3SzMveDVkL09j
      ay9yYzRRWnY1b0ZZeVRVaERBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE3cldyU2RHRUtuZkVh
      ZForcGxrQVpDNDFPeDVLYlZWRzNtdWw4akl6Cm9Rb0NJRjRvempJZnBqdUVJdHZMVDUxdDQ1bE4y
      R1JaV2hXVHRNUHhEdmV0cVdXegotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQK
      DENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMaghIKDUNvbnNlbnN1c1R5cGUS8BES
      5REKCGV0Y2RyYWZ0EtgRCsERChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijcazwgtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREFqQ0NBcW1nQXdJQkFnSVVBU0ZWbk1icTdTa25ITjNS
      c2p6NXlqS0VsaGd3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05W
      QkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJs
      Y21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekF6
      TURRek1qQXdXaGNOTWpNd056QXpNRFF6TnpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtH
      QTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlN
      UkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndi
      SGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTOGpQWG53
      NDAyc1diK0x3UGdxamtWVEdiTwowWGVhQXRyLzdWZ2dMRXYzQnJCWk15ZE9lYTZnVFlrT3JJbG95
      OWpqN1FjUUh5TGFMek85OVVXZjJ1UkJvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29N
      QjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVB
      akFBTUIwR0ExVWREZ1FXQkJRUG5ZTUxuTmkwNkJrNFRPY1Fpdko0eHRJeQp1akFmQmdOVkhTTUVH
      REFXZ0JRN0szL3g1ZC9PY2svcmM0UVp2NW9GWXlUVWhEQS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxj
      bVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allX
      d3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFX
      OXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVky
      aGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3
      SURSd0F3UkFJZ1F0Y2R1OFFhbXFFdndIZDEKT3ZHUHdyc3NUNWwwU3Fsd0FOMjdRRElCVmRzQ0lE
      NmgwU3pjTm13S1dxZ05hMHk0bnBCcTZZTlVUZE5zQmF3MwpWZStRWC9LMgotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiLPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQWpDQ0FxbWdB
      d0lCQWdJVUFTRlZuTWJxN1NrbkhOM1Jzano1eWpLRWxoZ3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpJd056QXpNRFF6TWpBd1doY05Nak13TnpBek1EUXpOekF3V2pCeE1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZR
      UURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkNBQVM4alBYbnc0MDJzV2IrTHdQZ3Fqa1ZUR2JPCjBYZWFBdHIvN1ZnZ0xF
      djNCckJaTXlkT2VhNmdUWWtPcklsb3k5amo3UWNRSHlMYUx6Tzk5VVdmMnVSQm80SUIKTURDQ0FT
      d3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdF
      RgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFQbllNTG5OaTA2Qms0VE9j
      UWl2SjR4dEl5CnVqQWZCZ05WSFNNRUdEQVdnQlE3SzMveDVkL09jay9yYzRRWnY1b0ZZeVRVaERB
      L0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdW
      eVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhK
      eklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpv
      aWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdW
      eVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnUXRjZHU4UWFtcUV2d0hkMQpPdkdQd3Jz
      c1Q1bDBTcWx3QU4yN1FESUJWZHNDSUQ2aDBTemNObXdLV3FnTmEweTRucEJxNllOVVRkTnNCYXcz
      ClZlK1FYL0syCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAga
      BkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcS
      DQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlu
      cyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMSvS8K
      C0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SyC4SsRcKD21hbnVmYWN0
      dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVPTjlzamZScHcvTlYyQ3UrMjdt
      d3RqUlEwZjh3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFn
      TUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1G
      amRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJ
      d056QXpNRFF5TmpNNVdoY05NalV3TkRJeU1EUXlOak01V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RF
      UE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9N
      CkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVs
      ZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJPckRFcFhCN21QNnkxRCtEYlVW
      TE1zT1hwQ000QjZ3c2phMQpFRGpGa1NzR2NrTmh5aUs4ZjVFTnJkV0hlNHpYanJvU2FVSGpJZjhs
      Q2xqNHkybEVuZytqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFE
      QWdHbU1CMEdBMVVkRGdRV0JCUjcvZVJTY21ESTlBTnMKblVGRk9Ta09rNUVpZlRBS0JnZ3Foa2pP
      UFFRREFnTkhBREJFQWlCSUJJZW93M0p4NHJ5cTdHYTBnOFQyOVhQdApwVUxwNnh4MTl6NzVuMUJP
      UFFJZ2UzRTRnZFVMbnRtdmZFdWtucms0MnVZRjRmdUY3eHlQcVlTVGxwb085M2s9Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVEND
      QXJlZ0F3SUJBZ0lVQVBubXlWT3BvcjJaRmFGOGVNOHFiZ09BNmxrd0NnWUlLb1pJemowRUF3SXcK
      WkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhM
      bTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekF6TURRek5EQXdXaGNOTWpNd056QXpN
      RFF6T1RBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpNNEx6Z3VO
      VFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdOVkJBc1RC
      V0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJaQlpHMXBi
      a0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemowREFRY0RR
      Z0FFM2pabzZTTHgvUmZ1QndjZElhRVVjNzduNXlnV0dzSmRCZ3VkczVxMFd0NFRSNlI2U3JXegps
      ZWIxcEptTHhQWU5tVDcrQVAxQWRiSnIydFNiNDZ5OXpLT0NBU0l3Z2dFZU1BNEdBMVVkRHdFQi93
      UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUZkZXV0JhS1FwaWVtU3NG
      SWxzUG5qeFZlYUNUQWYKQmdOVkhTTUVHREFXZ0JSNy9lUlNjbURJOUFOc25VRkZPU2tPazVFaWZU
      QWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMVlqWmpZbVkzWkRrNUxXSnpjSEYwTUlHWEJn
      Z3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0lt
      RmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1poWTNSMWNt
      VnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1IxY21WeUxX
      NWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGCkFp
      RUEyaVpiOVNRTjgvYWt5MFFySHFaaTRRNFZNY0EvVUtvbG5mTnc3bzdtdi84Q0lDdEhJWHh3S0p3
      ejNkR2UKZG5DWVpOdWZRSUVPQTcyNlhVTlYwdGxjWndDSAotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6
      Q0NBYktnQXdJQkFnSVVPTjlzamZScHcvTlYyQ3UrMjdtd3RqUlEwZjh3Q2dZSUtvWkl6ajBFQXdJ
      dwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3
      R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJO
      aExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056QXpNRFF5TmpNNVdoY05NalV3TkRJ
      eU1EUXlOak01V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4
      d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJv
      R0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0Nx
      R1NNNDlBd0VIQTBJQUJPckRFcFhCN21QNnkxRCtEYlVWTE1zT1hwQ000QjZ3c2phMQpFRGpGa1Nz
      R2NrTmh5aUs4ZjVFTnJkV0hlNHpYanJvU2FVSGpJZjhsQ2xqNHkybEVuZytqUWpCQU1BOEdBMVVk
      CkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUjcvZVJT
      Y21ESTlBTnMKblVGRk9Ta09rNUVpZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCSUJJZW93M0p4
      NHJ5cTdHYTBnOFQyOVhQdApwVUxwNnh4MTl6NzVuMUJPUFFJZ2UzRTRnZFVMbnRtdmZFdWtucms0
      MnVZRjRmdUY3eHlQcVlTVGxwb085M2s9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRt
      aW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBABGgZB
      ZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJN
      U1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVy
      TVNQGgZBZG1pbnMqBkFkbWlucxK2FgoKY2Fycmllck1TUBKnFhrDFAoDTVNQErsUErAUEq0UCgpj
      YXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJB
      Z0lVQ0hseXlMWDRXS2RiWVJiVloyYUFBTEJLQlVrd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGRE
      QWVGdzB5Ck1qQTNNRE13TkRJNE5ESmFGdzB5TlRBME1qSXdOREk0TkRKYU1Gb3hDekFKQmdOVkJB
      WVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1B
      NEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU3o4L2pkRVBjNzdtb25qQnc0VWplNFJJ
      anlQVG1SbXVhQ2xlL0pQb3REcHp5OUNOTy9CMkVmVVdxVXRiTEUKMi9PZGIxN2tMOWlPZEJCYmFm
      SFQwNWdjbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBq
      QWRCZ05WSFE0RUZnUVVSMGFtS3NoOHA4QkpiQTRrcnZLVGNERHhmNkV3Q2dZSUtvWkl6ajBFCkF3
      SURTQUF3UlFJZ1hGaFIvSGkySDdpbXIrSW1Dd1BiNEd4R1JXVHNEcE1IMmhla3Fqb282R0VDSVFD
      Yks4Y0UKRVYwbFc2K1c4ZFJtU1JJdXZpNno5OTdtZVJ0N3A3Z3o0MkRBRXc9PQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDN2pDQ0Fw
      U2dBd0lCQWdJVVRpTkIrdHhGYVB5eXpvMDZDRGQwQzIyeklzSXdDZ1lJS29aSXpqMEVBd0l3Cldq
      RUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5
      dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdW
      eUxXNWxkREFlRncweQpNakEzTURNd05EUXhNREJhRncweU16QTNNRE13TkRRMk1EQmFNSGd4Q3pB
      SkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURB
      T0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJG
      eWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtq
      T1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUeEdJZTEwVis1RVBBQUFNeWFYN2pYCm0yM25xeTUwakJ0
      a3NVZ0dDVnlnREo2US84V2IwVm0rdlN1dU14dkVPb2dMazdlcmQrYkltb3FKZGNtNTZHZEMKbzRJ
      QkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBP
      QkJZRQpGT2dJRU9wMFdiUG9FZU5obkVCTXAwWGxxaDBWTUI4R0ExVWRJd1FZTUJhQUZFZEdwaXJJ
      ZktmQVNXd09KSzd5CmszQXc4WCtoTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxUVTFZbUky
      TkdJMk5qZ3RPVFZxZHpZd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5SmhZbUZq
      TG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJw
      YjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFXNUFZMkZ5
      Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpqMEVBd0lE
      U0FBd1JRSWhBTFRNTkFQSkpZRjN0bzVVUUtVVTIweWZ6NUhwbjRQWmdwdXVSVU53bnMwbwpBaUJs
      WWdJczhYSWFZQjhoZTlQaThUNmx5QjlyZ3dmT2hsb1lQVUl5WUorZ0h3PT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVQ0hseXlMWDRXS2RiWVJiVloyYUFBTEJLQlVrd0NnWUlL
      b1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUURE
      QTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNRE13TkRJNE5ESmFGdzB5TlRBME1qSXdO
      REk0TkRKYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5C
      Z05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09Z
      MkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU3o4
      L2pkRVBjNzdtb25qQnc0VWplNFJJanlQVG1SbXVhQ2xlL0pQb3REcHp5OUNOTy9CMkVmVVdxVXRi
      TEUKMi9PZGIxN2tMOWlPZEJCYmFmSFQwNWdjbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01B
      NEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVSMGFtS3NoOHA4QkpiQTRrcnZLVGNE
      RHhmNkV3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJZ1hGaFIvSGkySDdpbXIrSW1Dd1BiNEd4R1JX
      VHNEcE1IMmhla3Fqb282R0VDSVFDYks4Y0UKRVYwbFc2K1c4ZFJtU1JJdXZpNno5OTdtZVJ0N3A3
      Z3o0MkRBRXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcKC0VuZG9yc2Vt
      ZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1JlYWRlcnMS
      KBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVycxIoEh4I
      ARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBII
      EgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVh
      dGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhIS
      CAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8a
      BkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0
      OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJf
      MBIAGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZB
      ZG1pbnMqBkFkbWlucxoOCgQKAgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
