apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: ssh://git@github.com/adityajoshi12/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.197.63.209:8200
      role: vault-role
      authpath: devsupplychain-net-auth
      secretprefix: secretv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIIyABkQDPEdqmnPeRi1KE07lZRFqGSNiDIBUBYMahfOpEqJeCp9eCpxeCngKWggBEAEaBgi6
      1NCWBiIKc3lzY2hhbm5lbCpAZDY1OTk1NGEyNjEyMjZiOTJmM2RhNTkzODk1YmRmMjIxNzFmODMx
      YmNhMDZkZTI0Zjk4NThjMDc1YzFiMzEwOBIaEhiHnuf5GpFxH2kaGRsY5CIRBGovM/NwSwwSn10K
      nF0SmV0SlSsKB09yZGVyZXISiSsS1hYKDnN1cHBseWNoYWluTVNQEsMWGs8UCgNNU1ASxxQSvBQS
      uRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVT0xkRHNPZC9LT252N3BsYlFMbWZTRDdtYnU4d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFM01UVXhNVFE0V2hjTk1qVXdOVEEyTVRVeE1UUTRX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJBRHVy
      THVZN1ZmSWJ6S25wWFdDTkRhSGpaZWowdHFnampJN3RXeDN0Z1RzTVNCV01BOVYKWkNHdEcvNytE
      bjQ4bE1haXMxcC85Ly81MGlKSmNLcmM0TVdqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFhReGJGeVFZU2lkWjVTZFpQZlg2aEFj
      dFR0VEFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQWxXRVZxeUU5WW5zTmpFOE9HUlNJY2MzZGt4
      eGNTUnduY01qOTg5U2gKUU9nQ0lRQ0s2aEJoZVg3WDJRT3U5eUxiRkIxb2pQZjFodHFiKytXWExG
      QzhOTmpBSkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKmCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNGpDQ0FvaWdBd0lCQWdJVUVEMVhvMUVETkdwT0sxUjJOZTMxUDBPZlNt
      d3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RTNNVFV4TkRBd1do
      Y05Nak13TnpFM01UVXhPVEF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRTdsZXl0dUlpb1lWVnl4Z2NTNjJVeTNO
      b1ZwdlBGSDRsClRUdEFLaU9wck1rYzcvNjZwb1d5Z0hwMzU4b2RuL2FNa3NpNDBsYnprbEFwL1Nx
      bVMrd0xqYU9DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUldTem5qRXJsNQpwS0xidGFqZy9KVzExUFBhSnpBZkJnTlZIU01FR0RB
      V2dCVFhReGJGeVFZU2lkWjVTZFpQZlg2aEFjdFR0VEFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDNaRFJrTnpZNVpHSmtMWFJqY1hFNU1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFNBQXcKUlFJaEFMajdtNktTU2hSdzlkUmRSMmFobVU2WXViZVhYeDI2NG1KcFVXV25QZlBX
      QWlBTW9RMktKY3I1MElrVgpIQ2dXYzIzKysvQzZ1VXZHbVhWSE1vKzhZR1ZuOXc9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK9QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQ0FUQ0NBYWFnQXdJQkFnSVVPTGREc09kL0tPbnY3cGxiUUxtZlNEN21idTh3
      Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlE
      VlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekUzTVRVeE1UUTRXaGNO
      TWpVd05UQTJNVFV4TVRRNFdqQmVNUXN3Q1FZRFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1
      Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFa
      QmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcK
      U000OUF3RUhBMElBQkFEdXJMdVk3VmZJYnpLbnBYV0NORGFIalplajB0cWdqakk3dFd4M3RnVHNN
      U0JXTUE5VgpaQ0d0Ry83K0RuNDhsTWFpczFwLzkvLzUwaUpKY0tyYzRNV2pRakJBTUE4R0ExVWRF
      d0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJUWFF4YkZ5
      UVlTaWRaNVNkWlBmWDZoQWN0VHRUQUsKQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBbFdFVnF5RTlZ
      bnNOakU4T0dSU0ljYzNka3h4Y1NSd25jTWo5ODlTaApRT2dDSVFDSzZoQmhlWDdYMlFPdTl5TGJG
      QjFvalBmMWh0cWIrK1dYTEZDOE5OakFKQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZB
      ZG1pbnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1T
      UBoGQWRtaW5zIjcKB1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1T
      UBoGQWRtaW5zIjcKB1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1T
      UBoGQWRtaW5zIjgKBkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQ
      EAEaBkFkbWlucyoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hh
      bm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAa
      BkFkbWlucxqCEgoNQ29uc2Vuc3VzVHlwZRLwERLlEQoIZXRjZHJhZnQS2BEKwREKGG9yZGVyZXIx
      LnN1cHBseWNoYWluLW5ldBCKNxrPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQWpD
      Q0FxbWdBd0lCQWdJVUtmVGtFeXNLV1lhbVhNYlc2Y3FnUEdIRHB0b3dDZ1lJS29aSXpqMEVBd0l3
      ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RTNNVFV4TkRBd1doY05Nak13TnpFM01UVXhPVEF3
      V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1
      Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3
      SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJtN1pRaTJKR2xqbjFTNzluZlY0RmlsUm1TCmRXZENBalBp
      YkNDSHN4WVM3MG0xY1pGaEszWDJkQXNlSTdQaFQzWmlRaVY2Ry9MT0dsNFBSYzJlOFZyV280SUIK
      TURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJC
      Z2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNINGZSVUt3RU5u
      QnVNL2VhckwzNGRDUERhCk5EQWZCZ05WSFNNRUdEQVdnQlRYUXhiRnlRWVNpZFo1U2RaUGZYNmhB
      Y3RUdFRBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NH
      bTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJ
      bUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVk
      RWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJ
      bTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnVWJGcDdXekZBTEZ1ajFrQwpz
      SkxwZXh5ejBwT0Fodi9QUEJBYlRKMVU1MGdDSUd0L0I0QWhzTDRYbkh2clJmNG8xSU5JU1hWakFV
      Q1g1V1JYCk9nTHFDbVdTCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIs8ILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVS2ZUa0V5c0tXWWFtWE1iVzZjcWdQ
      R0hEcHRvd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFM01UVXhO
      REF3V2hjTk1qTXdOekUzTVRVeE9UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVC
      eE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpE
      Z1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFH
      RnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUm03WlFpMkpHbGpu
      MVM3OW5mVjRGaWxSbVMKZFdkQ0FqUGliQ0NIc3hZUzcwbTFjWkZoSzNYMmRBc2VJN1BoVDNaaVFp
      VjZHL0xPR2w0UFJjMmU4VnJXbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0Ex
      VWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1C
      MEdBMVVkRGdRV0JCU0g0ZlJVS3dFTm5CdU0vZWFyTDM0ZENQRGEKTkRBZkJnTlZIU01FR0RBV2dC
      VFhReGJGeVFZU2lkWjVTZFpQZlg2aEFjdFR0VEEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1T
      NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1Clky
      OXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpv
      aUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0
      dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEUndB
      d1JBSWdVYkZwN1d6RkFMRnVqMWtDCnNKTHBleHl6MHBPQWh2L1BQQkFiVEoxVTUwZ0NJR3QvQjRB
      aHNMNFhuSHZyUmY0bzFJTklTWFZqQVVDWDVXUlgKT2dMcUNtV1MKLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICACBoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCA
      gIAxGICAQBoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxK9LwoLQ29uc29ydGl1bXMSrS8S4i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLILhKxFwoP
      bWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1TUBKBBi0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVU93RnNERC9rRTBX
      V21Cd1VreTJFdWRyU0g0OHdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4
      TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhR
      d0hoY05Nakl3TnpFM01UVXhNelV5V2hjTk1qVXdOVEEyTVRVeE16VXlXakJrTVFzd0NRWURWUVFH
      CkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFU
      QmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1Ix
      Y21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkUrSWNPcnZybUky
      bXVXcEJIZkVYbnVUZnNGQjdTeFhPcHVDCmFYTkZodWgycEZkTk43WE4zTWJoMDYzNGdpV0EvVmVj
      QlNOQnhZRldKYlhKdVVRZysyS2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQ
      QVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJUaWV1U1BUbVBlTzF1UgpOTEhMeno4LzZyelBhekFL
      QmdncWhrak9QUVFEQWdOSUFEQkZBaUJIbWN3TTB4TmpWVUFyUTRWY2V6S1dEc2tTCjM2RE1TYU9n
      cEw4aWtYc0Y0d0loQUl1cElaUGJDZU5FSmZZSE1JWDBtM3paY0FoQjdtY0hoMStPU05Wd0NwQzEK
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJREVUQ0NBcmVnQXdJQkFnSVVGSXRBUEtnVjB1Q1dYN2g1aGsvRTV6R09QcjB3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056RTNNVFV4TmpBd1doY05N
      ak13TnpFM01UVXlNVEF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNM
      ak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6QU1C
      Z05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZRUURE
      QlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6
      ajBEQVFjRFFnQUU3cFUwTDhjdm9la2l0dHpoLysweTZNSUdTSUltVnNlanZhVWQ5OGtMejZLbnQ5
      aVNITTQrCkg2VkpGSXZVcVZ0ZE51eTlGeHlyY2k1NURlYzhZdmg1bWFPQ0FTSXdnZ0VlTUE0R0Ex
      VWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNIdytwNytZ
      OUg0WTF5aXlYMFR0YTFKZnFBa1RBZgpCZ05WSFNNRUdEQVdnQlRpZXVTUFRtUGVPMXVSTkxITHp6
      OC82cnpQYXpBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTA0TmpWbVl6ZzVabVkxTFRoME9I
      WjRNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpvaWRI
      SjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldGdWRX
      WmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1poClkz
      UjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdO
      SUFEQkYKQWlFQXQrTjhxTk1oNzIvUXNmTGsxV1htT1J6QWpWeEtJdUc1UlVlMzBockxtZ0VDSUJE
      dXRvT1Z3RE1LcTlNTQovZUhpM2ZGMGpkaGN4NzVPUUw3SXYrMHA1alNPCi0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlDRERDQ0FiS2dBd0lCQWdJVU93RnNERC9rRTBXV21Cd1VreTJFdWRyU0g0OHdDZ1lJS29a
      SXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdO
      VkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpFM01UVXhNelV5V2hj
      Tk1qVXdOVEEyTVRVeE16VXlXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25W
      eWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhK
      bGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000
      OUFnRUdDQ3FHU000OUF3RUhBMElBQkUrSWNPcnZybUkybXVXcEJIZkVYbnVUZnNGQjdTeFhPcHVD
      CmFYTkZodWgycEZkTk43WE4zTWJoMDYzNGdpV0EvVmVjQlNOQnhZRldKYlhKdVVRZysyS2pRakJB
      TUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FX
      QkJUaWV1U1BUbVBlTzF1UgpOTEhMeno4LzZyelBhekFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUJI
      bWN3TTB4TmpWVUFyUTRWY2V6S1dEc2tTCjM2RE1TYU9ncEw4aWtYc0Y0d0loQUl1cElaUGJDZU5F
      SmZZSE1JWDBtM3paY0FoQjdtY0hoMStPU05Wd0NwQzEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJN
      U1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zErYWCgpjYXJyaWVyTVNQEqcWGsMUCgNNU1ASuxQS
      sBQSrRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NB
      WjZnQXdJQkFnSVVOZVJnYjJRR283TkV0cStpa0tHeS9UQlBiQmt3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFX
      VnlMVzVsZERBZUZ3MHkKTWpBM01UY3hOVEUxTlRSYUZ3MHlOVEExTURZeE5URTFOVFJhTUZveEN6
      QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJt
      UnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNp
      MXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFSNzNlQXZFS0JleTVOVWZz
      c0JVdTlOa3dzSFZSUkJzakova0RyRlVlVzJSTnZVQmo4V2gyWWtaWFQxYzdqKwpUbHlITTBDZkdV
      Vm9uMkF4bGRZUGE2MlZvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93
      UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXF2aXVnQnZ4SjZnTmRLb3dTc3JUWU9WeGY0VXdDZ1lJS29a
      SXpqMEUKQXdJRFNBQXdSUUloQUxXSDdOZkphOU9jcGJGclQ3NmNsR2hhSVFpc2lmeFpPNjVzcnp3
      TW5GbDhBaUE4ZEN2bApDQW0wc0VNQTNvMFNES3VEOHBlMXlZMkE5dmFhV0pXcW1TOVcyZz09Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUM3akNDQXBTZ0F3SUJBZ0lVVWNORCsyNUtjd1BGMDNEYm9tbDNtMnkxMUJZd0NnWUlLb1pJemow
      RUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1
      allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNVGN4TlRJeE1EQmFGdzB5TXpBM01UY3hOVEkyTURC
      YU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1
      a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFV
      RUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFGOG9ZZFZmNm9jNUxFSnd6L3FNelYKZGFQ
      MkRxd0lrN09kSHNNQ0ZqRzJZa1Fpa3ZTY3Bpdy9QRWgxWDhZaUxaQ01wZitraHB0aFVvbWRpei9o
      dCtCYgpvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3
      SFFZRFZSME9CQllFCkZKblZOUTZWNUFKNGI5RDBLZEpEaEM2U2U1WkRNQjhHQTFVZEl3UVlNQmFB
      RktyNHJvQWI4U2VvRFhTcU1FcksKMDJEbGNYK0ZNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6
      TFRVNU5XTTNOMlExT1dJdFpqSm1ibVl3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2
      ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1pt
      YVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0
      YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJ
      emowRUF3SURTQUF3UlFJaEFOVXhKVUtma1E3MW1sSGQwTFFTMnhNMEpVa2t0MjRlaUlxSm9laEdl
      STl1CkFpQXJ3eXZDYzdXU20wdDd5UG1aTVhXdFVVZHk3VEFFSUt2TU1pb2NEbFFRTlE9PQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVOZVJnYjJRR283TkV0cStpa0tHeS9UQlBi
      Qmt3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dG
      UVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01UY3hOVEUxTlRSYUZ3MHlO
      VEExTURZeE5URTFOVFJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWti
      MjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdB
      MVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkMKQUFSNzNlQXZFS0JleTVOVWZzc0JVdTlOa3dzSFZSUkJzakova0RyRlVlVzJSTnZVQmo4V2gy
      WWtaWFQxYzdqKwpUbHlITTBDZkdVVm9uMkF4bGRZUGE2MlZvMEl3UURBUEJnTlZIUk1CQWY4RUJU
      QURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXF2aXVnQnZ4SjZnTmRL
      b3dTc3JUWU9WeGY0VXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQUxXSDdOZkphOU9jcGJGclQ3
      NmNsR2hhSVFpc2lmeFpPNjVzcnp3TW5GbDhBaUE4ZEN2bApDQW0wc0VNQTNvMFNES3VEOHBlMXlZ
      MkE5dmFhV0pXcW1TOVcyZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoH
      V3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1p
      bnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNl
      bWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJz
      EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hh
      bm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdv
      cml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhAS
      Bgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHlj
      aGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQS
      CgoICgRWMl8wEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
