apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: ssh://git@github.com/adityajoshi12/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://40.80.95.60:8200
      role: vault-role
      authpath: devsupplychain-net-auth
      secretprefix: secretv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIES09GhJw2tQxy9oSEUIVg0rLFt3rfZ0L0mYd/kozgDOEppeCpdeCpReCngKWggBEAEaBgjE
      voSWBiIKc3lzY2hhbm5lbCpANGZkMTA2MTFiYzIwNmFiZThjODFjZTYyOGQzNTY2NDY1MDVlYjYy
      NGRmZDUxMmE1ZTMxMDhmNDAxZTM4OWM1MBIaEhhLKB4dseDtncsjGfC6235x/g6EtBVZ9DwSl10K
      lF0SkV0SjSsKB09yZGVyZXISgSsSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVSkIzSE1LMzJGU1k0b1FZL0MyRXV2d25MZXA4d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpBek1EUXlORE0zV2hjTk1qVXdOREl5TURReU5ETTNX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJQTXU5
      MTFUc2szTmZTZjBQVFR0TWFrTXpOTi83M0ZsWURYVjZ4akt0Yk0xUy85Vkx6OVkKdVZGcVR0V0dG
      YTZMbWxlVWZXU0VUZ20yMk5JZ3BKN2VJS0tqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUTdLMy94NWQvT2NrL3JjNFFadjVvRll5
      VFVoREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTdyV3JTZEdFS25mRWFkWitwbGtBWkM0MU94
      NUtiVlZHM211bDhqSXoKb1FvQ0lGNG96aklmcGp1RUl0dkxUNTF0NDVsTjJHUlpXaFdUdE1QeER2
      ZXRxV1d6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVRE95RDU5SHZEa2FOTUJHUFN4YU9rRGN1anBVd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpBek1EUXpNakF3V2hjTk1q
      TXdOekF6TURRek56QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNDJlMWFGLzhVYWxLMVVvWE5IdFdVK2lZRHJo
      d2Z4N2YKVHZ0Y1FBV0hVR2VUNzVVbkhKb1R2U094UFFvRTBFcEdZVmpSWGZxVlppc2tNdnFLTFlW
      S3A2T0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRVEFibVFBNlNWCmZTMU9qcGVTQ1BvYzlkd2s2ekFmQmdOVkhTTUVHREFXZ0JR
      N0szL3g1ZC9PY2svcmM0UVp2NW9GWXlUVWhEQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05UZG1aalZpTkdRNExXcHFiSEp3TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUwyUlJQSDNGeE1VK2hmUmFneWFVcldBTFI0MXJFYjJscVlZejFPOXRZYW9BaUI1
      VEFVRmt1dGliRXMwClk3U2JKc3IrRWRvZklvajVRZ1pEY01qZmF4cFBwdz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVUpCM0hNSzMyRlNZNG9RWS9DMkV1dnduTGVwOHdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056QXpNRFF5TkRNM1doY05NalV3
      TkRJeU1EUXlORE0zV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCUE11OTExVHNrM05mU2YwUFRUdE1ha016Tk4vNzNGbFlEWFY2eGpLdGJNMVMvOVZM
      ejlZCnVWRnFUdFdHRmE2TG1sZVVmV1NFVGdtMjJOSWdwSjdlSUtLalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlE3SzMveDVkL09j
      ay9yYzRRWnY1b0ZZeVRVaERBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE3cldyU2RHRUtuZkVh
      ZForcGxrQVpDNDFPeDVLYlZWRzNtdWw4akl6Cm9Rb0NJRjRvempJZnBqdUVJdHZMVDUxdDQ1bE4y
      R1JaV2hXVHRNUHhEdmV0cVdXegotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRp
      ZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGoISCg1Db25zZW5zdXNUeXBlEvAREuURCghldGNkcmFm
      dBLYEQrBEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3Gs8ILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVQVNGVm5NYnE3U2tuSE4zUnNqejV5aktFbGhn
      d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZ
      RFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpBek1EUXpNakF3V2hj
      Tk1qTXdOekF6TURRek56QXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRF
      dU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFR
      TEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1
      ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUzhqUFhudzQwMnNXYitMd1Bn
      cWprVlRHYk8KMFhlYUF0ci83VmdnTEV2M0JyQlpNeWRPZWE2Z1RZa09ySWxveTlqajdRY1FIeUxh
      THpPOTlVV2YydVJCbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFX
      TUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVk
      RGdRV0JCUVBuWU1Mbk5pMDZCazRUT2NRaXZKNHh0SXkKdWpBZkJnTlZIU01FR0RBV2dCUTdLMy94
      NWQvT2NrL3JjNFFadjVvRll5VFVoREEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dH
      Q0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kK
      YUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJ
      aXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdR
      dGNkdThRYW1xRXZ3SGQxCk92R1B3cnNzVDVsMFNxbHdBTjI3UURJQlZkc0NJRDZoMFN6Y05td0tX
      cWdOYTB5NG5wQnE2WU5VVGROc0JhdzMKVmUrUVgvSzIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoizwgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREFqQ0NBcW1nQXdJQkFnSVVBU0ZW
      bk1icTdTa25ITjNSc2p6NXlqS0VsaGd3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1D
      UjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lE
      VlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcK
      SGhjTk1qSXdOekF6TURRek1qQXdXaGNOTWpNd056QXpNRFF6TnpBd1dqQnhNUXN3Q1FZRFZRUUdF
      d0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtF
      d2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxj
      bVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJC
      d05DQUFTOGpQWG53NDAyc1diK0x3UGdxamtWVEdiTwowWGVhQXRyLzdWZ2dMRXYzQnJCWk15ZE9l
      YTZnVFlrT3JJbG95OWpqN1FjUUh5TGFMek85OVVXZjJ1UkJvNElCCk1EQ0NBU3d3RGdZRFZSMFBB
      UUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1C
      Z05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRUG5ZTUxuTmkwNkJrNFRPY1Fpdko0eHRJeQp1
      akFmQmdOVkhTTUVHREFXZ0JRN0szL3g1ZC9PY2svcmM0UVp2NW9GWXlUVWhEQS9CZ05WSFJFRU9E
      QTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRt
      VnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxr
      Rm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNq
      RXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0Nn
      WUlLb1pJemowRUF3SURSd0F3UkFJZ1F0Y2R1OFFhbXFFdndIZDEKT3ZHUHdyc3NUNWwwU3Fsd0FO
      MjdRRElCVmRzQ0lENmgwU3pjTm13S1dxZ05hMHk0bnBCcTZZTlVUZE5zQmF3MwpWZStRWC9LMgot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJ
      QmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMa
      BkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1pbnMSvS8K
      C0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SyC4SthYKCmNhcnJpZXJN
      U1ASpxYawxQKA01TUBK7FBKwFBKtFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUNIbHl5TFg0V0tkYllSYlZaMmFBQUxCS0JVa3dD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURW
      UVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakEzTURNd05ESTROREphRncweU5UQTBN
      akl3TkRJNE5ESmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhE
      ekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVB
      d3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpB
      QVN6OC9qZEVQYzc3bW9uakJ3NFVqZTRSSWp5UFRtUm11YUNsZS9KUG90RHB6eTlDTk8vQjJFZlVX
      cVV0YkxFCjIvT2RiMTdrTDlpT2RCQmJhZkhUMDVnY28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFR
      SC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVUjBhbUtzaDhwOEJKYkE0a3J2
      S1RjRER4ZjZFd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdYRmhSL0hpMkg3aW1yK0ltQ3dQYjRH
      eEdSV1RzRHBNSDJoZWtxam9vNkdFQ0lRQ2JLOGNFCkVWMGxXNitXOGRSbVNSSXV2aTZ6OTk3bWVS
      dDdwN2d6NDJEQUV3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQzdqQ0NBcFNnQXdJQkFnSVVUaU5CK3R4RmFQeXl6bzA2Q0RkMEMy
      MnpJc0l3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1S
      Y3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01ETXdORFF4TURCYUZ3
      MHlNekEzTURNd05EUTJNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1T
      NDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJB
      c1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJG
      eWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVHhHSWUxMFYr
      NUVQQUFBTXlhWDdqWAptMjNucXk1MGpCdGtzVWdHQ1Z5Z0RKNlEvOFdiMFZtK3ZTdXVNeHZFT29n
      TGs3ZXJkK2JJbW9xSmRjbTU2R2RDCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3
      R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRk9nSUVPcDBXYlBvRWVOaG5FQk1wMFhscWgw
      Vk1COEdBMVVkSXdRWU1CYUFGRWRHcGlySWZLZkFTV3dPSks3eQprM0F3OFgraE1DUUdBMVVkRVFR
      ZE1CdUNHV05oTFhSdmIyeHpMVFUxWW1JMk5HSTJOamd0T1RWcWR6WXdnWTBHCkNDb0RCQVVHQndn
      QkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lK
      MGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhz
      YldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0
      YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFNBQXdSUUloQUxUTU5BUEpKWUYzdG81VVFLVVUyMHlm
      ejVIcG40UFpncHV1UlVOd25zMG8KQWlCbFlnSXM4WElhWUI4aGU5UGk4VDZseUI5cmd3Zk9obG9Z
      UFVJeVlKK2dIdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkrp
      BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUNIbHl5TFg0
      V0tkYllSYlZaMmFBQUxCS0JVa3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4
      RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFL
      REFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakEz
      TURNd05ESTROREphRncweU5UQTBNakl3TkRJNE5ESmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdE
      UVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hR
      MkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQwpBQVN6OC9qZEVQYzc3bW9uakJ3NFVqZTRSSWp5UFRtUm11YUNs
      ZS9KUG90RHB6eTlDTk8vQjJFZlVXcVV0YkxFCjIvT2RiMTdrTDlpT2RCQmJhZkhUMDVnY28wSXdR
      REFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVG
      Z1FVUjBhbUtzaDhwOEJKYkE0a3J2S1RjRER4ZjZFd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdY
      RmhSL0hpMkg3aW1yK0ltQ3dQYjRHeEdSV1RzRHBNSDJoZWtxam9vNkdFQ0lRQ2JLOGNFCkVWMGxX
      NitXOGRSbVNSSXV2aTZ6OTk3bWVSdDdwN2d6NDJEQUV3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQ
      EAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJN
      U1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoG
      QWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1p
      bnMqBkFkbWlucxKxFwoPbWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVm
      YWN0dXJlck1TUBKBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lC
      QWdJVU9OOXNqZlJwdy9OVjJDdSsyN213dGpSUTBmOHdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtH
      QTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8K
      TVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1Z
      V04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpBek1EUXlOak01V2hjTk1qVXdOREl5TURReU5qTTVX
      akJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhE
      QVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZ
      MkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhB
      MElBQk9yREVwWEI3bVA2eTFEK0RiVVZMTXNPWHBDTTRCNndzamExCkVEakZrU3NHY2tOaHlpSzhm
      NUVOcmRXSGU0elhqcm9TYVVIaklmOGxDbGo0eTJsRW5nK2pRakJBTUE4R0ExVWQKRXdFQi93UUZN
      QU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJSNy9lUlNjbURJOUFOcwpu
      VUZGT1NrT2s1RWlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUJJQkllb3czSng0cnlxN0dhMGc4
      VDI5WFB0CnBVTHA2eHgxOXo3NW4xQk9QUUlnZTNFNGdkVUxudG12ZkV1a25yazQydVlGNGZ1Rjd4
      eVBxWVNUbHBvTzkzaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJREVUQ0NBcmVnQXdJQkFnSVVBUG5teVZPcG9yMlpGYUY4ZU04cWJn
      T0E2bGt3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRI
      VnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056
      QXpNRFF6TkRBd1doY05Nak13TnpBek1EUXpPVEF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdq
      QVlCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClpt
      RmpkSFZ5WlhJeEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21W
      eU1SOHcKSFFZRFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29a
      SXpqMENBUVlJS29aSQp6ajBEQVFjRFFnQUUzalpvNlNMeC9SZnVCd2NkSWFFVWM3N241eWdXR3NK
      ZEJndWRzNXEwV3Q0VFI2UjZTcld6CmxlYjFwSm1MeFBZTm1UNytBUDFBZGJKcjJ0U2I0Nnk5ektP
      Q0FTSXdnZ0VlTUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFV
      ZERnUVdCQlRmRldXQmFLUXBpZW1Tc0ZJbHNQbmp4VmVhQ1RBZgpCZ05WSFNNRUdEQVdnQlI3L2VS
      U2NtREk5QU5zblVGRk9Ta09rNUVpZlRBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAxWWpa
      alltWTNaRGs1TFdKemNIRjBNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdK
      aFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0Yw
      YVc5dQpJam9pYldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0
      YVc1QWJXRnVkV1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFL
      QmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQTJpWmI5U1FOOC9ha3kwUXJIcVppNFE0Vk1jQS9VS29s
      bmZOdzdvN212LzhDSUN0SElYeHdLSnd6M2RHZQpkbkNZWk51ZlFJRU9BNzI2WFVOVjB0bGNad0NI
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lCQWdJVU9OOXNqZlJwdy9OVjJDdSsyN213
      dGpSUTBmOHdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdN
      QmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZq
      ZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3
      TnpBek1EUXlOak01V2hjTk1qVXdOREl5TURReU5qTTVXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQ
      TUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00K
      REUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxk
      REJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk9yREVwWEI3bVA2eTFEK0RiVVZM
      TXNPWHBDTTRCNndzamExCkVEakZrU3NHY2tOaHlpSzhmNUVOcmRXSGU0elhqcm9TYVVIaklmOGxD
      bGo0eTJsRW5nK2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURB
      Z0dtTUIwR0ExVWREZ1FXQkJSNy9lUlNjbURJOUFOcwpuVUZGT1NrT2s1RWlmVEFLQmdncWhrak9Q
      UVFEQWdOSEFEQkVBaUJJQkllb3czSng0cnlxN0dhMGc4VDI5WFB0CnBVTHA2eHgxOXo3NW4xQk9Q
      UUlnZTNFNGdkVUxudG12ZkV1a25yazQydVlGNGZ1Rjd4eVBxWVNUbHBvTzkzaz0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRIT
      Cg9tYW51ZmFjdHVyZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAES
      AggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggB
      EgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYI
      ARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVh
      dGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoS
      Hwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      GiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRo
      bRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP//
      //8PGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMqBkFkbWlucxoOCgQKAgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
