apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: ssh://git@github.com/adityajoshi12/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://40.80.95.60:8200
      role: vault-role
      authpath: devsupplychain-net-auth
      secretprefix: secretv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaICUUo1rttGdOAGVxWfihbmX3I43zk/niHjrqXaN5HsI8EpZeCpNeCpBeCngKWggBEAEaBgjO
      hIWWBiIKc3lzY2hhbm5lbCpAZjllZDYzYTk0MzE3NmMzZGRmOWVlODM2ZmViOTk2OGY5NzVkN2Rk
      NDMyODU5NmQ2OTM4OTYzYWNiZDA4ZDg5ZRIaEhiqJBLFuxuMPuYgd1Ha/48mJuf17EvdGfkSk10K
      kF0SjV0SkSsKB09yZGVyZXIShSsSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVY0h1c1lRcWlENlJ4SWsxbjZqclJWR0VHUUI4d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpBek1EY3dNakU0V2hjTk1qVXdOREl5TURjd01qRTRX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJPWGpa
      SUhxSjl3aDdYSnduNnJyOWdRQnNydUNtMTNwc2tTWUdYZ0FTMm13MUhsMm1VUGkKaWVlSHBndUhh
      cS80Y1NBUWk2QkpYMVR2TmxpTGxXR2NISGVqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUllGMHpBekNmM3JqNXdhS3Z0THpXaEZL
      b1ZHekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCeGhnck5oVG1aa25VYUVmWEJkdnJIbVluaDBJ
      aUhEcG5LN0RqbXZRd1UKV1FJaEFKYXl1YjhDYW02d0VOQzczTGxOVS9LYmwzZUx3Z1JrUjJxenN4
      aUt0RW8yCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVUHJYNE5ncExlNHhXY2hWSTI2dnNUMUp2UWxjd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpBek1EY3dOREF3V2hjTk1q
      TXdOekF6TURjd09UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZ1VDdFE3dE1VeHhIdmgxdVRaS25rOXVMV0Fy
      RVg4UVEKRGc1MStRYTdLa00vckZpa04vWGZhS2Jxc2JaTENoL2hPNmcwaWh1U1pCdXUrREZjRXEw
      NlNxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUREdVK1ZXS3kzCmdlb3BmeGtuU2pFNy94ZmN5ekFmQmdOVkhTTUVHREFXZ0JS
      WUYwekF6Q2Yzcmo1d2FLdnRMeldoRktvVkd6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05UZG1aalZpTkdRNExYUTFkRzFpTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnRng5ODN0R2ZuRlI0TGNzbSt0cXF0UGJEWWRMRFJxeTVxcUE1YUpTeCtMZ0NJRTRL
      YVk1UDlnSlVTSitxCmRjVEQ5NGw4K2ZQQTlXSTV5ZllYU0d3aVdkRk0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVY0h1c1lRcWlENlJ4SWsxbjZqclJWR0VHUUI4d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpBek1EY3dNakU0V2hjTk1qVXdOREl5
      TURjd01qRTRXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJPWGpaSUhxSjl3aDdYSnduNnJyOWdRQnNydUNtMTNwc2tTWUdYZ0FTMm13MUhsMm1VUGkK
      aWVlSHBndUhhcS80Y1NBUWk2QkpYMVR2TmxpTGxXR2NISGVqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUllGMHpBekNmM3JqNXdh
      S3Z0THpXaEZLb1ZHekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCeGhnck5oVG1aa25VYUVmWEJk
      dnJIbVluaDBJaUhEcG5LN0RqbXZRd1UKV1FJaEFKYXl1YjhDYW02d0VOQzczTGxOVS9LYmwzZUx3
      Z1JrUjJxenN4aUt0RW8yCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2Fw
      YWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoI
      ZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVUFXRk0yRlVEVkE4RnVXMUR5TklB
      RFl4U21Ub3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdN
      Qmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5
      TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056QXpNRGN3
      TkRBd1doY05Nak13TnpBek1EY3dPVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVF
      QnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcK
      RGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGph
      R0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNjc05Qa1g5T3Iw
      TktOR3FzcG0ybjV6elR2CnAzaTh5QzkwUk54NDZ1Yi9jdi93L01abW9DYjluR1JydkFXQzRYc2lB
      OGY1V08xck5YckFibU1OZUdmbm80SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdB
      MVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFN
      QjBHQTFVZERnUVdCQlF1Wm5qeTdmdnhmRmxEbkFpanNId3lVVHpmClRUQWZCZ05WSFNNRUdEQVdn
      QlJZRjB6QXpDZjNyajV3YUt2dEx6V2hGS29WR3pBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlN
      UzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZ
      Mjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlq
      b2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFX
      NHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNB
      QXdSUUloQU55cHcxVHYvNDE1Yk1mWApGdzJqb09OamJEZGwvZDQ5R0tNeVVvMGI4RVlKQWlBUTBr
      ZnFBREtuWXZtTEt2SXB5aHpDREtMdWhIUVhtYlc4ClBMRXlSdUxhRnc9PQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdB
      d0lCQWdJVUFXRk0yRlVEVkE4RnVXMUR5TklBRFl4U21Ub3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpJd056QXpNRGN3TkRBd1doY05Nak13TnpBek1EY3dPVEF3V2pCeE1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZR
      UURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkNBQVNjc05Qa1g5T3IwTktOR3FzcG0ybjV6elR2CnAzaTh5QzkwUk54NDZ1
      Yi9jdi93L01abW9DYjluR1JydkFXQzRYc2lBOGY1V08xck5YckFibU1OZUdmbm80SUIKTURDQ0FT
      d3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdF
      RgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlF1Wm5qeTdmdnhmRmxEbkFp
      anNId3lVVHpmClRUQWZCZ05WSFNNRUdEQVdnQlJZRjB6QXpDZjNyajV3YUt2dEx6V2hGS29WR3pB
      L0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdW
      eVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhK
      eklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpv
      aWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdW
      eVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU55cHcxVHYvNDE1Yk1mWApGdzJqb09O
      amJEZGwvZDQ5R0tNeVVvMGI4RVlKQWlBUTBrZnFBREtuWXZtTEt2SXB5aHpDREtMdWhIUVhtYlc4
      ClBMRXlSdUxhRnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiA
      gIAIGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tW
      YWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1Jl
      YWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5z
      ErUvCgtDb25zb3J0aXVtcxKlLxLaLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsAuErEXCg9tYW51
      ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVUi8ySTFRVlpQbzZIS0tr
      Z2p6Uk5TeERiYnJzd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdO
      VkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1
      MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhj
      Tk1qSXdOekF6TURjd05ESXlXaGNOTWpVd05ESXlNRGN3TkRJeVdqQmtNUXN3Q1FZRFZRUUcKRXdK
      RFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05W
      QkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5
      TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCR2VpczkvZ0F4UU5Yd2tD
      ejk1RDVNNTM2NnllTTFINVZHOEgKUGd5dzY5TVJ5eGx1WkhLMlY5Ri9hRzgxTEgxMkloN2hYSzZr
      ZVJoL1pxWkZ4bmtpd2dxalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgv
      QkFRREFnR21NQjBHQTFVZERnUVdCQlMxbjI2ZGR5K0Q0cWw5CnBRUUJGM1VZaFZnQUtEQUtCZ2dx
      aGtqT1BRUURBZ05JQURCRkFpQm0zckxCRGIwTU1MVmk5ZEk0MWMrTzRmUVUKYUQza29FYnN3alZB
      dFc5WG9nSWhBTjk3Mm1lS2JmOGtIa09qUWM2NHp0MWc0aytvd0dIc1NCNDBLbWtQUEluVgotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlE
      RURDQ0FyZWdBd0lCQWdJVWY1bzF4dlBBRkhOR1MyNVRwWmU2dXczNXh6VXdDZ1lJS29aSXpqMEVB
      d0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1F
      Mk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpBek1EY3dOakF3V2hjTk1qTXdO
      ekF6TURjeE1UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRM
      emd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZC
      QXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJa
      RzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERB
      UWNEUWdBRUxPUzV4empHVGxDVDVSNEF6R0kxQ0VFUXlZUUhDbHlGVUJpSXFrUmx2VUhSbXRKLytn
      NWUKZ21aS1hrSDdONWd6cXFGZE1SZHYrSHNEdEJrNzdTSHY1cU9DQVNJd2dnRWVNQTRHQTFVZER3
      RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUjMzb2l2QzlVUzFD
      NG5idnpTNWt6bGF5WGVzVEFmCkJnTlZIU01FR0RBV2dCUzFuMjZkZHkrRDRxbDlwUVFCRjNVWWhW
      Z0FLREFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDFZalpqWW1ZM1pEazVMVzFvZERoa01J
      R1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpT
      SXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkz
      UjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNt
      VnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05IQURC
      RQpBaUJIdmkvTnB1ZXVMYmxJdkF1UE9mdFhIRTFnMUxXb3oxcTJid2ErVU0vcXBnSWdic1gwSHd4
      dkMyMVl2akxnCnR6YnVEUXlLYlEyUTNHclpCcXRLaFJFaFNSOD0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUNERENDQWJLZ0F3SUJBZ0lVUi8ySTFRVlpQbzZIS0trZ2p6Uk5TeERiYnJzd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekF6TURjd05ESXlXaGNOTWpV
      d05ESXlNRGN3TkRJeVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdO
      b01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pF
      Y01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdF
      R0NDcUdTTTQ5QXdFSEEwSUFCR2VpczkvZ0F4UU5Yd2tDejk1RDVNNTM2NnllTTFINVZHOEgKUGd5
      dzY5TVJ5eGx1WkhLMlY5Ri9hRzgxTEgxMkloN2hYSzZrZVJoL1pxWkZ4bmtpd2dxalFqQkFNQThH
      QTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlMx
      bjI2ZGR5K0Q0cWw5CnBRUUJGM1VZaFZnQUtEQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQm0zckxC
      RGIwTU1MVmk5ZEk0MWMrTzRmUVUKYUQza29FYnN3alZBdFc5WG9nSWhBTjk3Mm1lS2JmOGtIa09q
      UWM2NHp0MWc0aytvd0dIc1NCNDBLbWtQUEluVgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoG
      QWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBAB
      GgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1
      cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSrhYKCmNhcnJpZXJNU1ASnxYauxQKA01TUBKzFBKoFBKl
      FAoKY2Fycmllck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdB
      d0lCQWdJVUZpT04reFJ1cWFNbmVoYUlaU1VUcUxkOWFnY3dDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxX
      NWxkREFlRncweQpNakEzTURNd056QTJNak5hRncweU5UQTBNakl3TnpBMk1qTmFNRm94Q3pBSkJn
      TlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJq
      RVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpY
      UXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFGMUsva3puK045bDNjcTd6c2k4
      SURtSjRxUEZ6L1R5Sm91azMwZTB6c1grNmY4WGo1d3l3M1BPQmZFZDB2Ck1GZlJtVnRabmhPYzYr
      eFJxSnA2dld0cW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3
      SUJwakFkQmdOVkhRNEVGZ1FVWXZha2Qvd3AwZ1dxOFJxSHBnazR4OFdzaHNnd0NnWUlLb1pJemow
      RQpBd0lEUndBd1JBSWdHRFZ3WXNTLzVOUzJCbktRMmRNSVhkalg5V2NwMnJTdncya0JmOHhtdGJz
      Q0lEalFFd2FpCjlIZ2xKZ2lIZUREeE1PZmZ4TnNCc0tLOGdvVzVBMGtXQlUwNwotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDN2pDQ0Fw
      U2dBd0lCQWdJVVg1aTVQQksweEdMN0lNeSthU3c0SXcyb0xKa3dDZ1lJS29aSXpqMEVBd0l3Cldq
      RUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5
      dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdW
      eUxXNWxkREFlRncweQpNakEzTURNd056RXhNREJhRncweU16QTNNRE13TnpFMk1EQmFNSGd4Q3pB
      SkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURB
      T0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJG
      eWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtq
      T1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRaVVsaUwva3hONHlXT1dpYWhTZDRiCk5NTTZ2aENMYVFI
      YWY0K3VybGs1WHNkQkNSOWdKOGVlZmJVTFBoMjNBZHg4dGtBTSs4eXRhSUszZ05mUElZUEUKbzRJ
      QkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBP
      QkJZRQpGT1c2dkllYzU0MExibGlZWTV6cjIvbDNicitoTUI4R0ExVWRJd1FZTUJhQUZHTDJwSGY4
      S2RJRnF2RWFoNllKCk9NZkZySWJJTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxUVTFZbUky
      TkdJMk5qZ3RaSHAyT1hnd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5SmhZbUZq
      TG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJw
      YjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFXNUFZMkZ5
      Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpqMEVBd0lE
      U0FBd1JRSWhBTHVtY29iTVdBSVBzTi9EUnFhcjQwYzVZdWRVWlVtTmZ6TFNZdGJXS2dIVApBaUEx
      NU9BQmVwMVI3SVgweUsyNEVGY3YvSkNuSk1VeEVwdTM3S3VEd0VOSDdRPT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVRmlPTit4UnVxYU1uZWhhSVpTVVRxTGQ5YWdjd0NnWUlL
      b1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUURE
      QTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNRE13TnpBMk1qTmFGdzB5TlRBME1qSXdO
      ekEyTWpOYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5C
      Z05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09Z
      MkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUUYx
      Sy9rem4rTjlsM2NxN3pzaThJRG1KNHFQRnovVHlKb3VrMzBlMHpzWCs2ZjhYajV3eXczUE9CZkVk
      MHYKTUZmUm1WdFpuaE9jNit4UnFKcDZ2V3RxbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01B
      NEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVZdmFrZC93cDBnV3E4UnFIcGdrNHg4
      V3Noc2d3Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ0dEVndZc1MvNU5TMkJuS1EyZE1JWGRqWDlX
      Y3AyclN2dzJrQmY4eG10YnNDSURqUUV3YWkKOUhnbEpnaUhlRER4TU9mZnhOc0JzS0s4Z29XNUEw
      a1dCVTA3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgB
      EhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIe
      CAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIa
      EggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIG
      CAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9u
      UG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJf
      MBIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJs
      b2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJl
      c3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcS
      DQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlu
      cyoGQWRtaW5zGg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
