apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-net-ca-tools
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-net-ca-tools
  chart:
    git: ssh://git@github.com/adityajoshi12/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/catools
  values:
    metadata:
      namespace: carrier-net
      name: ca-tools
      component_type: peer
      org_name: carrier
      proxy: none
    annotations:  
      service:
      pvc:
      deployment:
    replicaCount: 1

    image:
      repository: hyperledger/fabric-ca-tools
      tag: 1.2.1
      pullPolicy: IfNotPresent
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://40.80.95.60:8200
      authpath: devcarrier-net-auth
      secretmsp: secretv2/data/crypto/peerOrganizations/carrier-net/users/admin/msp
      secrettls: secretv2/data/crypto/peerOrganizations/carrier-net/users/admin/tls
      secretorderer: secretv2/data/crypto/peerOrganizations/carrier-net/orderers
      secretpeer: secretv2/data/crypto/peerOrganizations/carrier-net/peers
      secretpeerorderertls: secretv2/data/crypto/peerOrganizations/carrier-net/orderer/tls
      secretambassador: secretv2/data/crypto/peerOrganizations/carrier-net/ambassador
      secretcert: secretv2/data/crypto/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: secretv2/data/crypto/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretcouchdb: secretv2/data/credentials/carrier-net/couchdb/carrier
      secretconfigfile: secretv2/data/crypto/peerOrganizations/carrier-net/msp/config
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: develop.local.com
      component_subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      cert_subject: O=Carrier/OU=Carrier/L=51.50,-0.13,London/C=GB
      component_country: GB
      component_state: London
      component_location: London
      ca_url: ca.carrier-net:7054

    orderers:
      name: orderer1-
    orderers_info:
      - name: orderer1
        path: "certs/orderer1-ca.crt"

    peers:
      name: peer0,-      
    peer_count: "1"

    checks:
      refresh_cert_value: False
