apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-net-ca
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-net-ca
  chart:
    git: ssh://git@github.com/adityajoshi12/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: carrier-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    deployment:
      annotations:
    annotations:  
      service:
      pvc:
 
    server:
      name: ca
      tlsstatus: true
      admin: carrier-admin 
  
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://40.80.95.60:8200
      authpath: devcarrier-net-auth
      secretcert: secretv2/data/crypto/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: secretv2/data/crypto/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretadminpass: secretv2/data/credentials/carrier-net/ca/carrier?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: peer
      external_url_suffix: develop.local.com
