apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-vaultkubenertes-job
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-vaultkubenertes-job
  chart:
    git: ssh://git@github.com/adityajoshi12/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: supplychain
      component_type: orderer
      namespace: supplychain-net    
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://144.126.254.182:8200
      authpath: devsupplychain-net-auth
      policy: vault-crypto-orderer-supplychain-net-ro
      secret_path: secretv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://98247a4a-0c9a-4977-83c9-f85bac0a9381.k8s.ondigitalocean.com
